# Generated by Django 5.1.7 on 2025-07-25 17:16

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('review', models.CharField(max_length=500)),
                ('rating', models.IntegerField(default=0)),
                ('post_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('short_discriptions', models.TextField()),
                ('discriptions', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock_quantity', models.CharField(max_length=50)),
                ('product_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_name', unique=True)),
                ('image_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('prd_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymart.category')),
            ],
        ),
    ]
