# Generated by Django 5.1.7 on 2025-07-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymart', '0002_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
    ]
