# Generated by Django 5.1.7 on 2025-07-27 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymart', '0004_add_to_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='mymart.product'),
        ),
    ]
