# Generated by Django 5.1.7 on 2025-08-02 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymart', '0006_remove_review_reviewer_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_address', models.CharField(max_length=200)),
                ('ship_city', models.CharField(max_length=100)),
                ('ship_state', models.CharField(max_length=100)),
                ('ship_zipcode', models.IntegerField()),
                ('ship_mobile', models.IntegerField()),
                ('ship_username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
