# Generated by Django 5.1.7 on 2025-08-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymart', '0007_shippingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='ship_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='ship_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='ship_mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='ship_zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
