# Generated by Django 5.1.7 on 2025-08-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymart', '0008_shippingdetails_ship_date_shippingdetails_ship_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetails',
            name='ship_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='ship_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='ship_state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
