# Generated by Django 5.1.7 on 2025-08-02 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymart', '0009_alter_shippingdetails_ship_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mymart.product'),
        ),
    ]
