# Generated by Django 5.1.7 on 2025-08-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymart', '0012_add_to_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prd_weight',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.ImageField(default=0, null=True, upload_to=''),
        ),
    ]
