# Generated by Django 5.1.7 on 2025-08-10 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymart', '0014_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prd_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mymart.category'),
        ),
    ]
