# Generated by Django 5.1.7 on 2025-08-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymart', '0015_alter_product_prd_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='ship_payment_method',
            field=models.CharField(choices=[('cash_deliv', 'Cash On Delivery'), ('online', 'Online')], default='cash_deliv', max_length=60),
        ),
    ]
