# Generated by Django 5.1.7 on 2025-08-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymart', '0016_shippingdetails_ship_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetails',
            name='ship_payment_method',
            field=models.CharField(choices=[('cash_deliv', 'Cash On Delivery'), ('online', 'Online')], default='cash_deliv', max_length=60, null=True),
        ),
    ]
