# Generated by Django 5.1.7 on 2025-08-20 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymart', '0017_alter_shippingdetails_ship_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='order_note',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='ship_product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mymart.product'),
        ),
    ]
