# Generated by Django 5.1.7 on 2025-08-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymart', '0018_shippingdetails_order_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='ship_product_name',
        ),
    ]
